const { google } = require('googleapis');
require('dotenv').config();

class GoogleCalendarHelper {
    constructor(oauth2Client = null) {
        // Delaying initialization if no client provided to ensure factory is available
        this._oauth2Client = oauth2Client;
    }

    /**
     * Getter for oauth2Client to ensure it's initialized
     */
    get oauth2Client() {
        if (!this._oauth2Client) {
            this._oauth2Client = this._createOAuth2Client();
        }
        return this._oauth2Client;
    }

    set oauth2Client(client) {
        this._oauth2Client = client;
    }

    /**
     * Set a custom OAuth2 client (useful for testing)
     */
    setOAuth2Client(client) {
        this.oauth2Client = client;
    }

    /**
     * Factory to create OAuth2 Client
     */
    _createOAuth2Client() {
        return new google.auth.OAuth2(
            process.env.GOOGLE_CLIENT_ID,
            process.env.GOOGLE_CLIENT_SECRET,
            process.env.GOOGLE_REDIRECT_URI
        );
    }

    /**
     * Internal helper to get authenticated client
     */
    _getAuth(pimpinan) {
        // We create a new instance to avoid state leakage between concurrent requests
        const auth = this._createOAuth2Client();

        auth.setCredentials({
            access_token: pimpinan.google_access_token,
            refresh_token: pimpinan.google_refresh_token,
            expiry_date: pimpinan.google_token_expiry
        });

        return auth;
    }

    /**
     * Generate Auth URL for Pimpinan
     */
    /**
     * Get Auth URL
     */
    getAuthUrl(id_pimpinan) {
        const url = this.oauth2Client.generateAuthUrl({
            access_type: 'offline', // Required for refresh token
            scope: ['https://www.googleapis.com/auth/calendar.events'],
            state: id_pimpinan, // Pass pimpinan ID to state
            prompt: 'consent' // Ensure we always get a refresh token
        });
        console.log(`[Google Auth] Generated Auth URL for Pimpinan ID: ${id_pimpinan}`);
        return url;
    }

    /**
     * Exchange code for tokens
     */
    async getTokens(code) {
        const { tokens } = await this.oauth2Client.getToken(code);
        return tokens;
    }

    /**
     * Create or Update Calendar Event
     */
    async syncEvent(pimpinan, agenda, existingEventId = null, titlePrefix = '') {
        try {
            console.log(`[Google Sync] Starting sync for Pimpinan: ${pimpinan.nama_pimpinan} (${pimpinan.id_pimpinan})`);
            
            if (!pimpinan.google_access_token) {
                console.warn(`[Google Sync] Skip sync for ${pimpinan.nama_pimpinan}: No access token`);
                return null;
            }

            const auth = this._getAuth(pimpinan);
            const calendar = google.calendar({ version: 'v3', auth });

            // Robust Date Parsing
            let dateStr = '';
            if (typeof agenda.tanggal_kegiatan === 'string') {
                // If it's already YYYY-MM-DD or similar, try to extract just the date part
                dateStr = agenda.tanggal_kegiatan.includes('T') ? agenda.tanggal_kegiatan.split('T')[0] : agenda.tanggal_kegiatan;
                // If it contains space (Postgres format), split by space
                dateStr = dateStr.includes(' ') ? dateStr.split(' ')[0] : dateStr;
            } else {
                // Handle Date object
                dateStr = new Date(agenda.tanggal_kegiatan).toLocaleString('sv-SE', { timeZone: 'Asia/Jakarta' }).split(' ')[0];
            }

            const formatTime = (time) => {
                if (!time) return '00:00';
                // Handle if Sequelize returns a Date object for TIME field
                if (time instanceof Date) {
                    return time.toTimeString().slice(0, 5);
                }
                const timeStr = String(time);
                const parts = timeStr.split(':');
                return `${parts[0].padStart(2, '0')}:${parts[1].padStart(2, '0')}`;
            };

            const startTime = formatTime(agenda.waktu_mulai);
            const endTime = formatTime(agenda.waktu_selesai);

            const eventTitle = `${titlePrefix}${agenda.nama_kegiatan}`;
            const event = {
                summary: `[SIMAP] ${eventTitle}`,
                location: agenda.lokasi_kegiatan || '-',
                description: `
Detail Agenda (SIMAP) :
- Perihal: ${agenda.perihal || '-'}
- Nama Kegiatan: ${agenda.nama_kegiatan || '-'}
- Waktu Mulai: ${agenda.waktu_mulai || '-'}
- Waktu Selesai: ${agenda.waktu_selesai || '-'}
- Lokasi Kegiatan: ${agenda.lokasi_kegiatan || '-'}

Generated by SIMAP System
`.trim(),
                start: {
                    dateTime: `${dateStr}T${startTime}:00`,
                    timeZone: 'Asia/Jakarta',
                },
                end: {
                    dateTime: `${dateStr}T${endTime}:00`,
                    timeZone: 'Asia/Jakarta',
                },
                reminders: {
                    useDefault: false,
                    overrides: [
                        { method: 'email', minutes: 24 * 60 },
                        { method: 'popup', minutes: 30 },
                    ],
                },
            };

            console.log(`[Google Sync] Event Details: ${event.summary} at ${event.start.dateTime}`);

            if (existingEventId) {
                console.log(`[Google Sync] Patching existing event: ${existingEventId}`);
                const res = await calendar.events.patch({
                    calendarId: 'primary',
                    eventId: existingEventId,
                    resource: event,
                });
                return res.data.id;
            } else {
                console.log(`[Google Sync] Inserting new event`);
                const res = await calendar.events.insert({
                    calendarId: 'primary',
                    resource: event,
                });
                return res.data.id;
            }
        } catch (error) {
            console.error('Calendar Sync Error', error);
            throw error;
        }
    }

    /**
     * Delete Calendar Event
     */
    async deleteEvent(pimpinan, eventId) {
        if (!eventId) return;
        try {
            console.log(`[Google Delete] Deleting event ${eventId} for Pimpinan: ${pimpinan.nama_pimpinan}`);
            if (!pimpinan.google_access_token) {
                console.warn(`[Google Delete] Skip delete for ${pimpinan.nama_pimpinan}: No access token`);
                return;
            }

            const auth = this._getAuth(pimpinan);
            const calendar = google.calendar({ version: 'v3', auth });

            await calendar.events.delete({
                calendarId: 'primary',
                eventId: eventId,
            });
            console.log(`[Google Delete] Successfully deleted event: ${eventId}`);
        } catch (error) {
            if (error.code !== 410 && error.code !== 404) {
                console.error('[Google Delete] Error:', error);
                throw error;
            } else {
                console.log(`[Google Delete] Event ${eventId} already deleted or not found`);
            }
        }
    }
}

module.exports = new GoogleCalendarHelper();
